application: mazlo-wgr
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon

- url: /.*
  script: wgr.py
